'''
CATCHING the RAISERROR


You need to select a product from the products table using a given product_id.

If the select statement doesn't find any product, you want to raise an error using the RAISERROR statement. You also need to catch possible errors in the execution.

For this exercise, the value of @product_id is 5.

Instructions 1/2
50 XP

- Set @product_id to 5.
- Use the RAISERROR statement with a severity of 11, a state of 1 and the given @product_id.

'''
BEGIN TRY
  DECLARE @product_id INT = 5
   IF NOT EXISTS(SELECT * FROM products WHERE product_id=@product_id)
      RAISERROR('No product with id %d.', 11, 1, @product_id)
    ELSE
      SELECT * FROM products WHERE product_id = @product_id
END TRY
-- Catch the error
BEGIN CATCH
 -- Select the error message
  SELECT ERROR_MESSAGE()
END CATCH

'''
Instructions 2/2
50 XP

Catch the error generated by the RAISERROR statement you coded.
Select the error message using the appropriate function.

'''
BEGIN TRY
  DECLARE @product_id INT = 5
   IF NOT EXISTS (SELECT * FROM products WHERE product_id=@product_id)
      RAISERROR('No product with id %d.', 11, 1, @product_id)
    ELSE
      SELECT * FROM products WHERE product_id = @product_id
END TRY
-- Catch the error
BEGIN CATCH
 -- Select the error message
  SELECT ERROR_MESSAGE()
END CATCH
