'''
Using monotonically_increasing_id()


monotonically_increasing_id is efficient at generating a column of integers that is always increasing. It is useful for creating a unique id per row. Which of the following sequences would not be generated by the monotonically_increasing_id operation?

Answer the question
50XP

Possible Answers

    - 1, 2, 3, 4, 5, 6, 7, 8

    - 1, 2, 3, 4, 8589934592, 8589934593, 8589934594, 8589934595

    - 1, 2, 3, 3, 4, 5, 5, 6

    - 8589934592, 8589934593, 8589934594, 8589934595, 8589934596, 8589934597, 8589934598, 8589934599

Answer : 1, 2, 3, 3, 4, 5, 5, 6

'''
